# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c9f2dae08ce0d37db022b21b202c7e9d"
name = "Wove Gift"
application_url = "https://wovegifts.com/shopify/dashboard"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "https://wovegifts.com/api/webhooks/giftcard-redeem"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "https://wovegifts.com/api/shopify/webhooks/uninstall"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://wovegifts.com/api/shopify/webhooks/compliance"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_gift_card_transactions,read_gift_cards,read_orders,read_products,write_customers,write_gift_cards,write_orders,write_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://wovegifts.com/api/shopify/auth/callback"
]

[pos]
embedded = false
