ALTER TABLE "Settlements"
ALTER COLUMN "totalSoldAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "redeemedAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "outstandingAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "commissionAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "breakageAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "vatAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "netPayable" TYPE DOUBLE PRECISION,
ALTER COLUMN "totalPaid" TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingAmount" TYPE DOUBLE PRECISION;

ALTER TABLE "Settlements"
ALTER COLUMN "totalPaid" SET DEFAULT 0,
ALTER COLUMN "remainingAmount" SET DEFAULT 0;
