ALTER TABLE "BrandTerms"
ALTER COLUMN "maxDiscount" TYPE DOUBLE PRECISION,
ALTER COLUMN "minOrderValue" TYPE DOUBLE PRECISION,
ALTER COLUMN "breakageShare" TYPE DOUBLE PRECISION;

ALTER TABLE "denominations"
ALTER COLUMN "value" TYPE DOUBLE PRECISION;

ALTER TABLE "vouchers"
ALTER COLUMN "denominationValue" TYPE DOUBLE PRECISION,
ALTER COLUMN "maxAmount" TYPE DOUBLE PRECISION,
ALTER COLUMN "minAmount" TYPE DOUBLE PRECISION;

ALTER TABLE "VoucherCode"
ALTER COLUMN "originalValue" TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingValue" TYPE DOUBLE PRECISION;

ALTER TABLE "VoucherRedemption"
ALTER COLUMN "amountRedeemed" TYPE DOUBLE PRECISION,
ALTER COLUMN "balanceAfter" TYPE DOUBLE PRECISION;

ALTER TABLE "Order"
ALTER COLUMN "amount" TYPE DOUBLE PRECISION,
ALTER COLUMN "subtotal" TYPE DOUBLE PRECISION,
ALTER COLUMN "discount" TYPE DOUBLE PRECISION,
ALTER COLUMN "totalAmount" TYPE DOUBLE PRECISION;

ALTER TABLE "promo_codes"
ALTER COLUMN "discountValue" TYPE DOUBLE PRECISION,
ALTER COLUMN "minOrderAmount" TYPE DOUBLE PRECISION;
